<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <ApplicationIcon>Resources\N1C1S1.ico</ApplicationIcon>
  </PropertyGroup>

  <PropertyGroup Label="Version">
    <VersionPrefix>0.9.0</VersionPrefix>
    <Authors>Carlos Alberto Costa Beppler (https://beppler.dev.br)</Authors>
    <Product>TrayLeds</Product>
    <Description>Tray Notification Leds</Description>
    <Copyright>© 2017-2026, Carlos Alberto Costa Beppler. All rights Reserved</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md"></None>
  </ItemGroup>

</Project>