<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
    <ApplicationIcon>Resources\N1C1S1.ico</ApplicationIcon>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishTrimmed>true</PublishTrimmed>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <PropertyGroup Label="Version">
    <VersionPrefix>0.9.0</VersionPrefix>
    <Authors>Carlos Alberto Costa Beppler (https://beppler.dev.br)</Authors>
    <Product>TrayLeds</Product>
    <Description>Tray Notification Leds</Description>
    <Copyright>© 2017-2026, Carlos Alberto Costa Beppler. All rights Reserved</Copyright>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\*.ico" />
  </ItemGroup>

</Project>